# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-29 01:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StreamInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(blank=True, default=None, max_length=50)),
                ('stream_method', models.CharField(blank=True, default=None, max_length=50)),
                ('src_path', models.CharField(blank=True, default=None, max_length=200)),
                ('dst_path', models.CharField(blank=True, default=None, max_length=200)),
                ('create_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
