# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-27 05:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('StreamSystem', '0002_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_login_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
