# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-27 05:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StreamSystem', '0003_user_last_login_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
    ]
